---
- name: create nginx config for mina-monitor
  copy:
    src: mina-monitor.nginx.conf
    dest: /etc/nginx/sites-enabled/mina-monitor.conf

- name: open http port 81
  command: ufw allow 81/tcp
  changed_when: false

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false

- name: 'Add nodejs apt key'
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: 'Add nodejs ppa for apt repo'
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ node_distribution }} main
    update_cache: yes

- name: 'Install nodejs'
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: Install mina monitor
  shell: 'curl -s https://raw.githubusercontent.com/olton/scripts/master/mina/monitor/client/install.sh | bash -s'

- name: Move mina monitor
  copy:
    remote_src: true
    src: /root/mina-monitor-client
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu

- name: Make config file
  template:
    src: config.json.j2
    dest: /home/ubuntu/mina-monitor-client/config.json
    owner: ubuntu
    group: ubuntu

- name: create mina_monitor systemd unit
  copy:
    src: mina-monitor.service
    dest: /etc/systemd/system/mina_monitor.service
    owner: root
    group: root
    mode: '600'

- name: start mina_monitor service
  systemd:
    name: mina_monitor
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
